export const DECK_TYPES = {
  Q_REPORT: 'q_report', SALES_PITCH: 'sales_pitch', MONTHLY_KPI: 'monthly_kpi',
  BOARD_UPDATE: 'board_update', PRODUCT_LAUNCH: 'product_launch', QBR: 'qbr', PORTFOLIO: 'portfolio',
};

export const MASTER_DECK_REGISTRY = [
  {
    id: DECK_TYPES.Q_REPORT, label: 'Quarterly Report',
    description: 'Full 30-slide quarterly business report with financials, KPIs and outlook',
    icon: 'BarChart3', recommendedStyle: 'corporate', slideCount: 30,
    tags: ['finance', 'leadership', 'board'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'agenda', label: 'Agenda', required: true },
      { type: 'section-overview', label: 'Executive Summary', required: true },
      { type: 'highlight-list', label: 'Key Highlights', required: true },
      { type: 'dashboard', label: 'Financial Overview', required: true, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Revenue Performance', required: true, infographic: 'revenue_bar_chart' },
      { type: 'content', label: 'Revenue by Region', required: false, infographic: 'region_pie_chart' },
      { type: 'table', label: 'Revenue Breakdown Table', required: true },
      { type: 'content', label: 'Gross Margin Trend', required: true, infographic: 'trend_line_chart' },
      { type: 'dashboard', label: 'Cost Analysis', required: false, infographic: 'kpi_scorecard' },
      { type: 'section-overview', label: 'Business Performance', required: true },
      { type: 'content', label: 'Sales Performance', required: true, infographic: 'sales_funnel' },
      { type: 'content', label: 'Pipeline & Forecast', required: true },
      { type: 'table', label: 'Top Deals / Accounts', required: true },
      { type: 'content', label: 'Customer Metrics', required: false },
      { type: 'content', label: 'Product Updates', required: true },
      { type: 'section-overview', label: 'Operations & People', required: false },
      { type: 'dashboard', label: 'Operations KPIs', required: false, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Team & Hiring', required: false },
      { type: 'content', label: 'Customer Success', required: false },
      { type: 'section-overview', label: 'Strategic Outlook', required: true },
      { type: 'content', label: 'Next Quarter Goals', required: true },
      { type: 'content', label: 'Key Initiatives', required: true, infographic: 'roadmap_timeline' },
      { type: 'content', label: 'Risks & Mitigations', required: true, infographic: 'risk_matrix' },
      { type: 'dashboard', label: 'Next Quarter Forecast', required: true, infographic: 'kpi_scorecard' },
      { type: 'section-overview', label: 'Appendix', required: false },
      { type: 'table', label: 'Detailed Financials', required: false },
      { type: 'table', label: 'Supporting Data', required: false },
      { type: 'content', label: 'Methodology / Notes', required: false },
      { type: 'thank-you', label: 'Thank You', required: true },
    ],
  },
  {
    id: DECK_TYPES.SALES_PITCH, label: 'Sales Pitch',
    description: 'Compelling sales deck with problem-solution narrative and ROI focus',
    icon: 'TrendingUp', recommendedStyle: 'bold', slideCount: 12,
    tags: ['sales', 'prospect', 'deal'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'content', label: 'The Problem', required: true },
      { type: 'content', label: 'Why Now', required: true },
      { type: 'section-overview', label: 'Our Solution', required: true },
      { type: 'content', label: 'How It Works', required: true, infographic: 'process_flow' },
      { type: 'highlight-list', label: 'Key Benefits', required: true },
      { type: 'dashboard', label: 'ROI & Business Case', required: true, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Case Study / Proof', required: true },
      { type: 'table', label: 'Pricing / Packages', required: true },
      { type: 'content', label: 'Implementation Plan', required: false, infographic: 'roadmap_timeline' },
      { type: 'highlight-list', label: 'Why Choose Us', required: true },
      { type: 'thank-you', label: "Let's Get Started", required: true },
    ],
  },
  {
    id: DECK_TYPES.MONTHLY_KPI, label: 'Monthly KPI Report',
    description: 'Operations dashboard with KPIs, trends and action items',
    icon: 'Activity', recommendedStyle: 'modern', slideCount: 10,
    tags: ['ops', 'monthly', 'metrics'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'dashboard', label: 'KPI Summary', required: true, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Revenue & Growth', required: true, infographic: 'revenue_bar_chart' },
      { type: 'content', label: 'Operational Metrics', required: true, infographic: 'trend_line_chart' },
      { type: 'table', label: 'Team Performance', required: true },
      { type: 'content', label: 'Key Wins', required: true },
      { type: 'content', label: 'Blockers & Risks', required: true, infographic: 'risk_matrix' },
      { type: 'highlight-list', label: 'Action Items', required: true },
      { type: 'content', label: 'Next Month Focus', required: true },
      { type: 'thank-you', label: 'Thank You', required: true },
    ],
  },
  {
    id: DECK_TYPES.BOARD_UPDATE, label: 'Board Update',
    description: 'Executive board update: strategic priorities, risks and decisions needed',
    icon: 'Briefcase', recommendedStyle: 'minimal', slideCount: 14,
    tags: ['board', 'executive', 'strategy'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'agenda', label: 'Agenda', required: true },
      { type: 'section-overview', label: 'Executive Summary', required: true },
      { type: 'highlight-list', label: 'Key Highlights', required: true },
      { type: 'dashboard', label: 'Company Scorecard', required: true, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Financial Summary', required: true },
      { type: 'content', label: 'Strategic Progress', required: true },
      { type: 'content', label: 'Key Risks', required: true, infographic: 'risk_matrix' },
      { type: 'content', label: 'Decisions Required', required: true },
      { type: 'content', label: 'Outlook', required: true },
      { type: 'section-overview', label: 'Discussion Items', required: false },
      { type: 'table', label: 'Appendix Data', required: false },
      { type: 'thank-you', label: 'Thank You', required: true },
    ],
  },
  {
    id: DECK_TYPES.PRODUCT_LAUNCH, label: 'Product Launch',
    description: 'Internal or external product launch deck with roadmap and go-to-market',
    icon: 'Rocket', recommendedStyle: 'modern', slideCount: 14,
    tags: ['product', 'launch', 'gtm'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'content', label: 'Vision & Mission', required: true },
      { type: 'content', label: 'Market Opportunity', required: true },
      { type: 'section-overview', label: 'The Product', required: true },
      { type: 'content', label: 'Core Features', required: true },
      { type: 'content', label: 'Demo / Screenshots', required: true },
      { type: 'content', label: 'Technical Architecture', required: false, infographic: 'process_flow' },
      { type: 'section-overview', label: 'Go To Market', required: true },
      { type: 'content', label: 'Target Segments', required: true },
      { type: 'content', label: 'Launch Roadmap', required: true, infographic: 'roadmap_timeline' },
      { type: 'table', label: 'Pricing Strategy', required: true },
      { type: 'dashboard', label: 'Success Metrics', required: true, infographic: 'kpi_scorecard' },
      { type: 'highlight-list', label: 'Team & Resources', required: false },
      { type: 'thank-you', label: 'Launch Day', required: true },
    ],
  },
  {
    id: DECK_TYPES.QBR, label: 'QBR (Quarterly Business Review)',
    description: 'Customer-facing QBR: value delivered, usage data, renewal and expansion',
    icon: 'RefreshCw', recommendedStyle: 'corporate', slideCount: 14,
    tags: ['customer', 'renewal', 'csm'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'agenda', label: 'Agenda', required: true },
      { type: 'highlight-list', label: 'Partnership Highlights', required: true },
      { type: 'dashboard', label: 'Usage & Adoption', required: true, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Value Delivered', required: true },
      { type: 'content', label: 'Key Outcomes', required: true },
      { type: 'table', label: 'Support & SLA Summary', required: false },
      { type: 'section-overview', label: 'Looking Ahead', required: true },
      { type: 'content', label: 'Roadmap Preview', required: true, infographic: 'roadmap_timeline' },
      { type: 'content', label: 'Expansion Opportunities', required: false },
      { type: 'highlight-list', label: 'Recommended Next Steps', required: true },
      { type: 'table', label: 'Renewal Summary', required: false },
      { type: 'content', label: 'Open Items / Q&A', required: false },
      { type: 'thank-you', label: 'Thank You', required: true },
    ],
  },
  {
    id: DECK_TYPES.PORTFOLIO, label: 'Portfolio / Capability Deck',
    description: 'Company or product portfolio showcase with credentials and case studies',
    icon: 'Layout', recommendedStyle: 'glass', slideCount: 12,
    tags: ['company', 'credentials', 'showcase'],
    slideSequence: [
      { type: 'title', label: 'Cover', required: true },
      { type: 'content', label: 'About Us', required: true },
      { type: 'highlight-list', label: 'Our Capabilities', required: true },
      { type: 'section-overview', label: 'Our Work', required: true },
      { type: 'content', label: 'Case Study 1', required: true },
      { type: 'content', label: 'Case Study 2', required: true },
      { type: 'content', label: 'Case Study 3', required: false },
      { type: 'dashboard', label: 'Impact Numbers', required: true, infographic: 'kpi_scorecard' },
      { type: 'content', label: 'Technology & Tools', required: false },
      { type: 'highlight-list', label: 'Why Partner With Us', required: true },
      { type: 'table', label: 'Engagement Models', required: false },
      { type: 'thank-you', label: "Let's Talk", required: true },
    ],
  },
];

export const getDeckById = (id) => MASTER_DECK_REGISTRY.find((d) => d.id === id);
export const getDeckSlideCount = (id) => getDeckById(id)?.slideSequence.length || 0;
